# Generated by Django 3.1.6 on 2021-09-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calypso_verify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qr',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='qr',
            name='first_verified',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
